version: "3"
services:
  centos-sysctl:
    build: .
    image: centos-sysctl:7

  # This service MUST have the name "kdc-kadmin" otherwise every kerberos client won't be able to talk with the KDC.
  # If you would like to change the name edit the file configureKerberosClient.sh and change the configurations
  # "kdc" and "admin_server" in the /etc/krb5.conf section.
  kdc-kadmin:
    build: ./kdc-kadmin
    env_file: kerberos.env
    privileged: true
    environment:
      - SUPPORTED_ENCRYPTION_TYPES: "aes256-cts:normal aes128-cts:normal des3-hmac-sha1:normal arcfour-hmac:normal camellia256-cts:normal camellia128-cts:normal des-hmac-sha1:normal des-cbc-md5:normal des-cbc-crc:normal"
      - KDC_DOMAIN: bigdatafqa.internal.timbrasil.com.br
      - REALM: HDPFQADLKSNE
      - KADMIN_PRINCIPAL: admin/admin
      - KADMIN_PASSWORD: EMCFQA@root02
      - MASTER_KDC: snelnxy12
      - SLAVE_KDC: snelnxy13
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - "/dev/urandom:/dev/random"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

#  kerberos-client:
#    build: ./kerberos-client
#    env_file: kerberos.env
#    depends_on:
#      - kdc-kadmin


# NOTE:
#  "env_file: kerberos.env" is optional.
#  In case no .env file is supplied, nor any environment variable is set, the following values will be used:
#   REALM=EXAMPLE.COM
#   SUPPORTED_ENCRYPTION_TYPES=aes256-cts-hmac-sha1-96:normal
#   KADMIN_PRINCIPAL=kadmin/admin
#   KADMIN_PASSWORD=MITiys4K5
#volumes:
#